

services:
  db:
    image: postgres:15
    environment:
      RAILS_ENV: development 
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "cron -f & bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      user: "${UID}:${GID}" 

volumes:
  db_data:

